; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
; Tối ưu bộ nhớ
board_build.flash_mode = qio
board_build.f_cpu = 240000000L

; Tăng kích thước stack cho các task
board_build.arduino.stack_size = 8192

; Tự động nạp và chạy ngay
upload_speed = 921600
upload_protocol = esptool

; Tùy chọn để debug (có thể comment khi không cần)
; build_type = debug
; monitor_filters = esp32_exception_decoder

; Tối ưu compiler flags
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue